services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx8g"  # 配置 Elasticsearch 的内存
    ports:
      - "9200:9200"  # 映射到本地的 9200 端口
    volumes:
      - ./data:/usr/share/elasticsearch/data  # 数据持久化

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"  # 映射到本地的 5601 端口（Kibana 的端口）

  logstash:
    image: docker.elastic.co/logstash/logstash:8.17.0
    container_name: logstash
    depends_on:
      - elasticsearch
    volumes:
      - ./custom-logstash.conf:/usr/share/logstash/pipeline/logstash.conf  # 将本地 Logstash 配置文件挂载到容器内
      - ./merged_products.csv:/data/merged_products.csv  # 将数据文件挂载到容器内
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"  # 配置 Logstash 的内存
