services:
  pgsql:
    image: docker.io/pgvector/pgvector:pg17
    restart: always
    shm_size: 128mb
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
